# Generated by Django 4.2.2 on 2023-06-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Talim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ism_Familiya', models.CharField(max_length=100)),
                ('Vaqti', models.DateTimeField(auto_now_add=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('Tekshiruvchi', models.BooleanField(default=False)),
            ],
        ),
    ]
